---
# tasks file for mytomdeploy
- name: removing old files from server
  file:
    path: /usr/share/tomcat/webapps/{{ item }}
    state: absent
  with_items:
    - mahaLogin
    - mahaLogin.war 
  
- name: deploying a java project to tomcat server
  get_url:
    url: https://s3.amazonaws.com/maha4iac/mahaLogin.war
    dest: /usr/share/tomcat/webapps/
    force_basic_auth: yes
  notify: restartTomcat