---
- hosts: webservers
  become: yes
  tasks:
  - name: install java on ubuntu
    apt:
     name: "{{javaonubuntu}}"
     present: yes
    when: ansible_os_family =="Debian"
  - name: installing java on redhat
    yum:
     name: "{{javaonredhat}}"
     state: present
    when: ansible_os_family =="RedHat"