---
- hosts: all
  become: yes
  tasks:
  - name: installing git, tree and wget on ubuntu
    apt:
     name: "{{ items }}"
     state: present
    with_items:
      - git
      - tree
      - wget
    when: ansible_os_family =="Debian"
  - name: installing git, tree and wget on redhat
    yum:
     name: "{{ items }}"
     state: present
    with_items: 
      - git
      - tree
      - wget
    when: ansible_os_family =="RedHat"