---
- hosts: redhatos
  become: yes
  tasks: 
  - name: executing linuc command
    command: hostname -f
    register: myregister
  - name: display result stored in myregister
    debug:
     msg: "{{myregister}}"

  - name: installing git based on command result
    yum:
      name: "{{mygit}}"
      state: present
    when: myregister.stderr ==""

    