---
- hosts: webservers
  become: yes
  tasks:
  - name: installing webserver on ubuntu
    apt:
     name: "{{webserveronubuntu}}"
     state: present
    when: ansible_os_family =="Debian"
  
  - name: installing webserver on redhat
    yum:
     name: "{{webserveronredhat}}"
     state: present
    when: ansible_os_family =="RedHat"

  - name: removing git on redhat
    yum:
      name: "{{mygit}}"
      state: absent
    when: ansible_os_family =="RedHat"