---
- hosts: all
  become: yes
  tasks:
   - name: installing webserver
     apt:
       name: apache2
       state: present
   - name : starting weebserver
     service:
       name: apache2
       state: started