---
- hosts: all
  become: yes
  tasks:
  - name: installing webserver on ubuntu
    apt:
     name: apache2
     state: present
    when: ansible_os_family =="Debian"
  
  - name: installing webserver on redhat
    yum:
     name: httpd
     state: present
    when: ansible_os_family =="RedHat"