---
- hosts: redhatos
  become: yes
  tasks:
  - name: installing server on redhat os
    yum:
     name: httpd
     state: present
    notify: startinghttpd
  - name: copy index file into all nodes
    template:
      src: myindex.j2
      dest: /var/www/html/index.html
    notify: startinghttpd 
  handlers:
   - name: startinghttpd
     service:
       name: httpd
       state: restarted