---
- hosts: redhatos
  become: yes
  tasks:
  - name: installing server on redhat os
    yum:
     name: httpd
     state: present
  - name: starting webservers
    service:
     name: httpd
     state: restarted 
  - name: copy index file into all nodes
    template:
      src: myindex.j2
      dest: /var/www/html/index.html
  
  - name: starting webservers
    service:
      name: httpd
      state: restarted